const STORAGE_KEY='rg-manual-review-v1';
const defaultState={reviewer:'',notes:[],answers:[],newParts:[]};
let state=loadState();
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=p=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;
const slug=s=>String(s??'').trim().toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
function loadState(){try{return {...defaultState,...JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')}}catch{return {...defaultState}}}
function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));$('#saveState').textContent=`Salvato · ${new Date().toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'})}`;renderAll()}
function getReviewer(){const n=$('#reviewerName').value.trim();if(!n){alert('Inserisci prima il nome del revisore.');$('#reviewerName').focus();return null}return n}
function renderAll(){renderManual();renderQuestions();renderNewParts();renderContributions()}
function renderManual(){const q=$('#manualSearch').value.trim().toLowerCase();const root=$('#manualRoot');root.innerHTML=MANUAL.chapters.map(ch=>{const chapterId=`chapter-${slug(ch.id)}`;const sections=ch.sections.map(sec=>{const paragraphs=sec.paragraphs.filter(p=>!q||`${sec.id} ${sec.title} ${p.text}`.toLowerCase().includes(q));if(!paragraphs.length)return'';const sectionId=`section-${slug(sec.id)}`;return `<h3 id="${sectionId}" class="section-title">${esc(sec.id)} ${esc(sec.title)}</h3>${paragraphs.map(p=>{const count=state.notes.filter(n=>n.paragraphId===p.id).length;return `<div class="paragraph"><div><div class="pid">${esc(p.id)}${count?`<span class="note-count">${count} note</span>`:''}</div><div class="paragraph-text">${esc(p.text)}</div></div><button data-note="${esc(p.id)}" data-section="${esc(sec.id)}">Aggiungi nota</button></div>`}).join('')}`}).join('');if(!sections)return'';return `<details id="${chapterId}" class="chapter" open><summary>${esc(ch.id)}. ${esc(ch.title)}</summary><div class="chapter-content">${sections}</div></details>`}).join('')||'<div class="empty">Nessun risultato.</div>';root.querySelectorAll('[data-note]').forEach(b=>b.onclick=()=>openNote(b.dataset.note,b.dataset.section));renderManualIndex(q)}
function renderManualIndex(query=''){const root=$('#manualIndexRoot');if(!root)return;const q=query.trim().toLowerCase();root.innerHTML=MANUAL.chapters.map(ch=>{const visibleSections=ch.sections.filter(sec=>!q||`${ch.id} ${ch.title} ${sec.id} ${sec.title} ${sec.paragraphs.map(p=>p.text).join(' ')}`.toLowerCase().includes(q));if(!visibleSections.length)return'';return `<div class="index-chapter"><button class="index-chapter-link" data-scroll="chapter-${slug(ch.id)}"><span>${esc(ch.id)}</span>${esc(ch.title)}</button>${visibleSections.map(sec=>`<button class="index-section-link" data-scroll="section-${slug(sec.id)}"><span>${esc(sec.id)}</span>${esc(sec.title)}</button>`).join('')}</div>`}).join('')||'<p class="index-empty">Nessun elemento.</p>';root.querySelectorAll('[data-scroll]').forEach(b=>b.onclick=()=>{const target=document.getElementById(b.dataset.scroll);if(!target)return;const chapter=target.matches('details')?target:target.closest('details');if(chapter)chapter.open=true;target.scrollIntoView({behavior:'smooth',block:'start'})})}
function renderQuestions(){const filter=$('#questionFilter').value;const root=$('#questionsRoot');const qs=QUESTIONS.filter(q=>{const answered=state.answers.some(a=>a.questionId===q.id);return filter==='all'||(filter==='open'&&!answered)||(filter==='answered'&&answered)});root.innerHTML=qs.map(q=>{const answers=state.answers.filter(a=>a.questionId===q.id);return `<article class="card"><span class="badge">${esc(q.sectionId||'Generale')}</span><span class="badge">${answers.length?'con risposta':'aperta'}</span><h3>${esc(q.title)}</h3><p>${esc(q.prompt)}</p>${q.prompts?.length?`<ul>${q.prompts.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:''}<button data-answer="${esc(q.id)}">Rispondi</button>${answers.length?`<div class="answer-list"><strong>Risposte salvate in questo browser</strong>${answers.map(a=>`<p><span class="badge">${esc(a.confidence)}</span><strong>${esc(a.author)}</strong><br>${esc(a.text)}</p>`).join('')}</div>`:''}</article>`}).join('')||'<div class="empty">Nessuna domanda in questa vista.</div>';root.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>openAnswer(b.dataset.answer))}
function renderNewParts(){const root=$('#newPartsRoot');root.innerHTML=`<h3 style="margin-top:30px">Nuove parti salvate (${state.newParts.length})</h3>${state.newParts.map(p=>`<article class="card"><span class="badge">${esc(p.type)}</span><span class="badge">certezza ${esc(p.confidence)}</span><h3>${esc(p.title)}</h3>${p.suggestedSection?`<div class="meta">Area suggerita: ${esc(p.suggestedSection)}</div>`:''}<p>${esc(p.text)}</p><div class="meta">${esc(p.author)} · ${new Date(p.createdAt).toLocaleString('it-IT')}${p.machine?` · ${esc(p.machine)}`:''}</div><div class="contribution-actions"><button data-delete-newpart="${p.id}" class="danger">Elimina</button></div></article>`).join('')||'<div class="empty">Nessuna nuova parte inserita.</div>'}`;root.querySelectorAll('[data-delete-newpart]').forEach(b=>b.onclick=()=>{state.newParts=state.newParts.filter(x=>x.id!==b.dataset.deleteNewpart);saveState()})}
function renderContributions(){const root=$('#contributionsRoot');const notes=state.notes.map(n=>`<article class="card"><span class="badge">${esc(n.type)}</span><span class="badge">certezza ${esc(n.confidence)}</span><h3>${esc(n.sectionId)} · ${esc(n.paragraphId)}</h3><p>${esc(n.text)}</p><div class="meta">${esc(n.author)} · ${new Date(n.createdAt).toLocaleString('it-IT')}${n.machine?` · ${esc(n.machine)}`:''}</div><div class="contribution-actions"><button data-delete-note="${n.id}" class="danger">Elimina</button></div></article>`).join('');const answers=state.answers.map(a=>{const q=QUESTIONS.find(x=>x.id===a.questionId);return `<article class="card"><span class="badge">risposta</span><span class="badge">certezza ${esc(a.confidence)}</span><h3>${esc(q?.title||a.questionId)}</h3><p>${esc(a.text)}</p><div class="meta">${esc(a.author)} · ${new Date(a.createdAt).toLocaleString('it-IT')}${a.machine?` · ${esc(a.machine)}`:''}</div><div class="contribution-actions"><button data-delete-answer="${a.id}" class="danger">Elimina</button></div></article>`}).join('');const parts=state.newParts.map(p=>`<article class="card"><span class="badge">nuova parte</span><span class="badge">${esc(p.type)}</span><h3>${esc(p.title)}</h3><p>${esc(p.text)}</p><div class="meta">${esc(p.author)} · ${new Date(p.createdAt).toLocaleString('it-IT')}</div><div class="contribution-actions"><button data-delete-newpart="${p.id}" class="danger">Elimina</button></div></article>`).join('');root.innerHTML=`<h3>Note al manuale (${state.notes.length})</h3>${notes||'<div class="empty">Nessuna nota inserita.</div>'}<h3 style="margin-top:30px">Risposte tecniche (${state.answers.length})</h3>${answers||'<div class="empty">Nessuna risposta inserita.</div>'}<h3 style="margin-top:30px">Nuove parti (${state.newParts.length})</h3>${parts||'<div class="empty">Nessuna nuova parte inserita.</div>'}`;root.querySelectorAll('[data-delete-note]').forEach(b=>b.onclick=()=>{state.notes=state.notes.filter(x=>x.id!==b.dataset.deleteNote);saveState()});root.querySelectorAll('[data-delete-answer]').forEach(b=>b.onclick=()=>{state.answers=state.answers.filter(x=>x.id!==b.dataset.deleteAnswer);saveState()});root.querySelectorAll('[data-delete-newpart]').forEach(b=>b.onclick=()=>{state.newParts=state.newParts.filter(x=>x.id!==b.dataset.deleteNewpart);saveState()})}
function openNote(paragraphId,sectionId){if(!getReviewer())return;const p=MANUAL.chapters.flatMap(c=>c.sections).flatMap(s=>s.paragraphs).find(x=>x.id===paragraphId);const f=$('#noteForm');f.reset();f.paragraphId.value=paragraphId;f.sectionId.value=sectionId;$('#noteTarget').textContent=`${paragraphId} · ${(p?.text||'').slice(0,90)}…`;$('#noteDialog').showModal()}
function openAnswer(questionId){if(!getReviewer())return;const q=QUESTIONS.find(x=>x.id===questionId);const f=$('#answerForm');f.reset();f.questionId.value=questionId;$('#answerTarget').textContent=q?.title||questionId;$('#answerDialog').showModal()}
$('#noteForm').addEventListener('submit',e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));const author=getReviewer();if(!author)return;state.notes.push({id:uid('N'),author,createdAt:new Date().toISOString(),...d,materials:d.materials.split(',').map(x=>x.trim()).filter(Boolean)});$('#noteDialog').close();saveState()});
$('#answerForm').addEventListener('submit',e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));const author=getReviewer();if(!author)return;state.answers.push({id:uid('A'),author,createdAt:new Date().toISOString(),...d});$('#answerDialog').close();saveState()});
$('#newPartForm').addEventListener('submit',e=>{e.preventDefault();const author=getReviewer();if(!author)return;const d=Object.fromEntries(new FormData(e.currentTarget));state.newParts.push({id:uid('P'),author,createdAt:new Date().toISOString(),status:'submitted',processedAt:null,...d});e.currentTarget.reset();saveState();alert('Nuova parte salvata. Verrà inclusa nell’esportazione JSON.')});
document.querySelectorAll('.close-dialog').forEach(b=>b.onclick=()=>b.closest('dialog').close());
document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.view').forEach(v=>v.classList.add('hidden'));$('#'+b.dataset.view).classList.remove('hidden')});
$('#reviewerName').value=state.reviewer;$('#reviewerName').addEventListener('change',e=>{state.reviewer=e.target.value.trim();saveState()});
$('#manualSearch').addEventListener('input',renderManual);$('#questionFilter').addEventListener('change',renderQuestions);
$('#exportBtn').onclick=()=>{const payload={schemaVersion:'1.1',app:'RG Manual Review',exportedAt:new Date().toISOString(),manual:{title:MANUAL.title,version:MANUAL.version,sourceRevision:MANUAL.sourceRevision},reviewer:state.reviewer,notes:state.notes,answers:state.answers,newParts:state.newParts};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`rg-manual-review_${(state.reviewer||'revisore').replace(/\s+/g,'-').toLowerCase()}_${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)};
$('#importInput').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{const data=JSON.parse(await file.text());const notes=Array.isArray(data.notes)?data.notes:[];const answers=Array.isArray(data.answers)?data.answers:[];const newParts=Array.isArray(data.newParts)?data.newParts:[];state.notes=[...state.notes,...notes.filter(n=>!state.notes.some(x=>x.id===n.id))];state.answers=[...state.answers,...answers.filter(a=>!state.answers.some(x=>x.id===a.id))];state.newParts=[...state.newParts,...newParts.filter(p=>!state.newParts.some(x=>x.id===p.id))];saveState();alert(`Importate ${notes.length} note, ${answers.length} risposte e ${newParts.length} nuove parti.`)}catch{alert('Il file selezionato non è un export valido.')}e.target.value=''};
$('#clearBtn').onclick=()=>{if(confirm('Cancellare tutte le note, le risposte e le nuove parti salvate in questo browser?')){state.notes=[];state.answers=[];state.newParts=[];saveState()}};
renderAll();