const STORAGE_KEY='rg-manual-review-v1';
const defaultState={reviewer:'',notes:[],answers:[],newParts:[],outbox:[],syncedContributionIds:[]};
let state=loadState();
let isFlushing=false;
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=p=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;
const slug=s=>String(s??'').trim().toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
function migrateAnswers(answers=[]){const map={'Q-003':'Q-002','Q-004':'Q-002','Q-005':'Q-002'};return answers.map(a=>({...a,questionId:map[a.questionId]||a.questionId}))}
function cleanContribution(item){const {confidence,machine,materials,conditions,...clean}=item||{};return clean}
function loadState(){try{const stored={...defaultState,...JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')};return {...stored,notes:(stored.notes||[]).map(cleanContribution),answers:migrateAnswers(stored.answers||[]).map(cleanContribution),newParts:(stored.newParts||[]).map(cleanContribution),outbox:Array.isArray(stored.outbox)?stored.outbox:[],syncedContributionIds:Array.isArray(stored.syncedContributionIds)?stored.syncedContributionIds:[]}}catch{return {...defaultState}}}
function persist(render=true){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));if(render)renderAll()}
function setSyncState(text){const el=$('#saveState');if(el)el.textContent=text}
function getReviewer(){const n=$('#reviewerName').value.trim();if(!n){alert('Inserisci prima il nome del revisore.');$('#reviewerName').focus();return null}return n}
function contributionKind(item){if(item.paragraphId)return'note';if(item.questionId)return'answer';return'new_part'}
function makeEvent(action,item){return{event_id:action==='create'?`${item.id}:create`:`${item.id}:delete:${Date.now()}-${Math.random().toString(36).slice(2,7)}`,contribution_id:item.id,contribution_type:contributionKind(item),action,reviewer:item.author||state.reviewer||'',manual_revision:MANUAL.sourceRevision,payload:cleanContribution(item),client_created_at:item.createdAt||new Date().toISOString()}}
function queueEvent(action,item){const event=makeEvent(action,item);if(!state.outbox.some(x=>x.event_id===event.event_id))state.outbox.push(event)}
function queueUnsyncedExisting(){[...state.notes,...state.answers,...state.newParts].forEach(item=>{if(!state.syncedContributionIds.includes(item.id)&&!state.outbox.some(x=>x.event_id===`${item.id}:create`))queueEvent('create',item)});persist(false)}
async function flushOutbox(){if(isFlushing||!state.outbox.length){if(!state.outbox.length)setSyncState('Database condiviso · sincronizzato');return}const cfg=window.RG_SUPABASE;if(!cfg?.restUrl||!cfg?.publishableKey){setSyncState('Database non configurato');return}isFlushing=true;setSyncState(`Salvataggio online… ${state.outbox.length} in coda`);try{while(state.outbox.length){const event=state.outbox[0];const response=await fetch(`${cfg.restUrl}/review_contribution_events?on_conflict=event_id`,{method:'POST',headers:{apikey:cfg.publishableKey,Authorization:`Bearer ${cfg.publishableKey}`,'Content-Type':'application/json',Prefer:'resolution=ignore-duplicates,return=minimal'},body:JSON.stringify(event)});if(!response.ok){const detail=await response.text().catch(()=>String(response.status));throw new Error(`${response.status} ${detail}`)}state.outbox.shift();if(event.action==='create'&&!state.syncedContributionIds.includes(event.contribution_id))state.syncedContributionIds.push(event.contribution_id);persist(false)}setSyncState(`Salvato online · ${new Date().toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'})}`)}catch(error){console.error('Supabase sync failed',error);setSyncState(`In coda locale · ${state.outbox.length} da sincronizzare`)}finally{isFlushing=false}}
function saveAndSync(){persist(true);setSyncState(`Salvataggio online… ${state.outbox.length} in coda`);flushOutbox()}
function renderAll(){renderManual();renderQuestions();renderNewParts();renderContributions()}
function renderTable(table,sectionId){const count=state.notes.filter(n=>n.paragraphId===table.id).length;return `<div class="manual-table-card"><div class="table-head"><div><div class="pid">${esc(table.id)}${count?`<span class="note-count">${count} note</span>`:''}</div><h4>${esc(table.title)}</h4></div><button data-note="${esc(table.id)}" data-section="${esc(sectionId)}">Aggiungi nota</button></div><div class="table-scroll"><table><thead><tr>${table.headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${table.rows.map(r=>`<tr>${r.map(c=>`<td>${esc(c)}</td>`).join('')}</tr>`).join('')}</tbody></table></div></div>`}
function renderBlock(p,sec){if(p.kind==='subheading')return `<h4 class="subsection-title">${esc(p.text)}</h4>`;const count=state.notes.filter(n=>n.paragraphId===p.id).length;const cls=p.kind==='list'?'paragraph-text list-line':'paragraph-text';return `<div class="paragraph"><div><div class="pid">${esc(p.id)}${count?`<span class="note-count">${count} note</span>`:''}</div><div class="${cls}">${esc(p.text)}</div></div><button data-note="${esc(p.id)}" data-section="${esc(sec.id)}">Aggiungi nota</button></div>`}
function renderManual(){const q=$('#manualSearch').value.trim().toLowerCase();const root=$('#manualRoot');root.innerHTML=MANUAL.chapters.map(ch=>{const chapterId=`chapter-${slug(ch.id)}`;const sections=ch.sections.map(sec=>{const searchable=`${sec.id} ${sec.title} ${sec.paragraphs.map(p=>p.text).join(' ')}`.toLowerCase();if(q&&!searchable.includes(q))return'';const sectionId=`section-${slug(sec.id)}`;const blocks=sec.paragraphs.filter(p=>!q||`${sec.id} ${sec.title} ${p.text}`.toLowerCase().includes(q)).map(p=>renderBlock(p,sec)).join('');const tables=(typeof MANUAL_TABLES!=='undefined'?(MANUAL_TABLES[sec.id]||[]):[]).filter(t=>!q||`${t.title} ${t.headers.join(' ')} ${t.rows.flat().join(' ')}`.toLowerCase().includes(q)).map(t=>renderTable(t,sec.id)).join('');if(!blocks&&!tables)return'';return `<h3 id="${sectionId}" class="section-title">${esc(sec.id)} ${esc(sec.title)}</h3>${blocks}${tables}`}).join('');if(!sections)return'';return `<details id="${chapterId}" class="chapter" open><summary>${esc(ch.id)}. ${esc(ch.title)}</summary><div class="chapter-content">${sections}</div></details>`}).join('')||'<div class="empty">Nessun risultato.</div>';root.querySelectorAll('[data-note]').forEach(b=>b.onclick=()=>openNote(b.dataset.note,b.dataset.section));renderManualIndex(q);const rev=$('#sourceRevision');if(rev)rev.textContent=`Revisione Drive importata: ${MANUAL.sourceRevision}`}
function renderManualIndex(query=''){const root=$('#manualIndexRoot');if(!root)return;const q=query.trim().toLowerCase();root.innerHTML=MANUAL.chapters.map(ch=>{const visibleSections=ch.sections.filter(sec=>!q||`${ch.id} ${ch.title} ${sec.id} ${sec.title} ${sec.paragraphs.map(p=>p.text).join(' ')}`.toLowerCase().includes(q));if(!visibleSections.length)return'';return `<div class="index-chapter"><button class="index-chapter-link" data-scroll="chapter-${slug(ch.id)}"><span>${esc(ch.id)}</span>${esc(ch.title)}</button>${visibleSections.map(sec=>`<button class="index-section-link" data-scroll="section-${slug(sec.id)}"><span>${esc(sec.id)}</span>${esc(sec.title)}</button>`).join('')}</div>`}).join('')||'<p class="index-empty">Nessun elemento.</p>';root.querySelectorAll('[data-scroll]').forEach(b=>b.onclick=()=>{const target=document.getElementById(b.dataset.scroll);if(!target)return;const chapter=target.matches('details')?target:target.closest('details');if(chapter)chapter.open=true;target.scrollIntoView({behavior:'smooth',block:'start'})})}
function renderQuestions(){const filter=$('#questionFilter').value;const root=$('#questionsRoot');const qs=QUESTIONS.filter(q=>{const answered=state.answers.some(a=>a.questionId===q.id);return filter==='all'||(filter==='open'&&!answered)||(filter==='answered'&&answered)});root.innerHTML=qs.map(q=>{const answers=state.answers.filter(a=>a.questionId===q.id);return `<article class="card"><span class="badge">${esc(q.sectionId||'Generale')}</span><span class="badge">${answers.length?'con risposta locale':'aperta'}</span><h3>${esc(q.title)}</h3><p>${esc(q.prompt)}</p>${q.prompts?.length?`<div class="question-trace"><strong>Spunti da considerare nella risposta</strong><ul>${q.prompts.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`:''}<button data-answer="${esc(q.id)}">Scrivi una risposta argomentata</button>${answers.length?`<div class="answer-list"><strong>Risposte inserite da questo browser</strong>${answers.map(a=>`<p><strong>${esc(a.author)}</strong><br>${esc(a.text)}</p>`).join('')}</div>`:''}</article>`}).join('')||'<div class="empty">Nessuna domanda in questa vista.</div>';root.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>openAnswer(b.dataset.answer))}
function renderNewParts(){const root=$('#newPartsRoot');root.innerHTML=`<h3 style="margin-top:30px">Nuove parti inserite da questo browser (${state.newParts.length})</h3>${state.newParts.map(p=>`<article class="card"><span class="badge">${esc(p.type)}</span><h3>${esc(p.title)}</h3>${p.suggestedSection?`<div class="meta">Area suggerita: ${esc(p.suggestedSection)}</div>`:''}<p>${esc(p.text)}</p><div class="meta">${esc(p.author)} · ${new Date(p.createdAt).toLocaleString('it-IT')}</div><div class="contribution-actions"><button data-delete-newpart="${p.id}" class="danger">Elimina</button></div></article>`).join('')||'<div class="empty">Nessuna nuova parte inserita.</div>'}`;root.querySelectorAll('[data-delete-newpart]').forEach(b=>b.onclick=()=>deleteContribution('newParts',b.dataset.deleteNewpart))}
function renderContributions(){const root=$('#contributionsRoot');const notes=state.notes.map(n=>`<article class="card"><span class="badge">${esc(n.type)}</span><h3>${esc(n.sectionId)} · ${esc(n.paragraphId)}</h3><p>${esc(n.text)}</p><div class="meta">${esc(n.author)} · ${new Date(n.createdAt).toLocaleString('it-IT')}</div><div class="contribution-actions"><button data-delete-note="${n.id}" class="danger">Elimina</button></div></article>`).join('');const answers=state.answers.map(a=>{const q=QUESTIONS.find(x=>x.id===a.questionId);return `<article class="card"><span class="badge">risposta</span><h3>${esc(q?.title||a.questionId)}</h3><p>${esc(a.text)}</p><div class="meta">${esc(a.author)} · ${new Date(a.createdAt).toLocaleString('it-IT')}</div><div class="contribution-actions"><button data-delete-answer="${a.id}" class="danger">Elimina</button></div></article>`}).join('');const parts=state.newParts.map(p=>`<article class="card"><span class="badge">nuova parte</span><span class="badge">${esc(p.type)}</span><h3>${esc(p.title)}</h3><p>${esc(p.text)}</p><div class="meta">${esc(p.author)} · ${new Date(p.createdAt).toLocaleString('it-IT')}</div><div class="contribution-actions"><button data-delete-newpart="${p.id}" class="danger">Elimina</button></div></article>`).join('');root.innerHTML=`<h3>Note al manuale (${state.notes.length})</h3>${notes||'<div class="empty">Nessuna nota inserita.</div>'}<h3 style="margin-top:30px">Risposte tecniche (${state.answers.length})</h3>${answers||'<div class="empty">Nessuna risposta inserita.</div>'}<h3 style="margin-top:30px">Nuove parti (${state.newParts.length})</h3>${parts||'<div class="empty">Nessuna nuova parte inserita.</div>'}`;root.querySelectorAll('[data-delete-note]').forEach(b=>b.onclick=()=>deleteContribution('notes',b.dataset.deleteNote));root.querySelectorAll('[data-delete-answer]').forEach(b=>b.onclick=()=>deleteContribution('answers',b.dataset.deleteAnswer));root.querySelectorAll('[data-delete-newpart]').forEach(b=>b.onclick=()=>deleteContribution('newParts',b.dataset.deleteNewpart))}
function deleteContribution(collection,id){const item=state[collection].find(x=>x.id===id);if(!item)return;queueEvent('delete',item);state[collection]=state[collection].filter(x=>x.id!==id);saveAndSync()}
function openNote(paragraphId,sectionId){if(!getReviewer())return;const p=MANUAL.chapters.flatMap(c=>c.sections).flatMap(s=>s.paragraphs).find(x=>x.id===paragraphId);const t=typeof MANUAL_TABLES!=='undefined'?Object.values(MANUAL_TABLES).flat().find(x=>x.id===paragraphId):null;const f=$('#noteForm');f.reset();f.paragraphId.value=paragraphId;f.sectionId.value=sectionId;$('#noteTarget').textContent=`${paragraphId} · ${((p?.text||t?.title||'')).slice(0,90)}${(p?.text||t?.title||'').length>90?'…':''}`;$('#noteDialog').showModal()}
function openAnswer(questionId){if(!getReviewer())return;const q=QUESTIONS.find(x=>x.id===questionId);const f=$('#answerForm');f.reset();f.questionId.value=questionId;$('#answerTarget').textContent=q?.title||questionId;$('#answerDialog').showModal()}
$('#noteForm').addEventListener('submit',e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));const author=getReviewer();if(!author)return;const item={id:uid('N'),author,createdAt:new Date().toISOString(),...d};state.notes.push(item);queueEvent('create',item);$('#noteDialog').close();saveAndSync()});
$('#answerForm').addEventListener('submit',e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));const author=getReviewer();if(!author)return;const item={id:uid('A'),author,createdAt:new Date().toISOString(),...d};state.answers.push(item);queueEvent('create',item);$('#answerDialog').close();saveAndSync()});
$('#newPartForm').addEventListener('submit',e=>{e.preventDefault();const author=getReviewer();if(!author)return;const d=Object.fromEntries(new FormData(e.currentTarget));const item={id:uid('P'),author,createdAt:new Date().toISOString(),status:'submitted',processedAt:null,...d};state.newParts.push(item);queueEvent('create',item);e.currentTarget.reset();saveAndSync();alert('Nuova parte registrata e inviata al database condiviso.')});
document.querySelectorAll('.close-dialog').forEach(b=>b.onclick=()=>b.closest('dialog').close());
document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.view').forEach(v=>v.classList.add('hidden'));$('#'+b.dataset.view).classList.remove('hidden')});
$('#reviewerName').value=state.reviewer;$('#reviewerName').addEventListener('change',e=>{state.reviewer=e.target.value.trim();persist(false)});
$('#manualSearch').addEventListener('input',renderManual);$('#questionFilter').addEventListener('change',renderQuestions);
$('#exportBtn').onclick=()=>{const payload={schemaVersion:'1.4',app:'RG Manual Review',exportedAt:new Date().toISOString(),manual:{title:MANUAL.title,version:MANUAL.version,sourceRevision:MANUAL.sourceRevision},reviewer:state.reviewer,notes:state.notes,answers:state.answers,newParts:state.newParts};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`rg-manual-review_${(state.reviewer||'revisore').replace(/\s+/g,'-').toLowerCase()}_${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)};
$('#importInput').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{const data=JSON.parse(await file.text());const notes=(Array.isArray(data.notes)?data.notes:[]).map(cleanContribution);const answers=migrateAnswers(Array.isArray(data.answers)?data.answers:[]).map(cleanContribution);const newParts=(Array.isArray(data.newParts)?data.newParts:[]).map(cleanContribution);const added=[];notes.forEach(n=>{if(!state.notes.some(x=>x.id===n.id)){state.notes.push(n);added.push(n)}});answers.forEach(a=>{if(!state.answers.some(x=>x.id===a.id)){state.answers.push(a);added.push(a)}});newParts.forEach(p=>{if(!state.newParts.some(x=>x.id===p.id)){state.newParts.push(p);added.push(p)}});added.forEach(item=>queueEvent('create',item));saveAndSync();alert(`Importati e messi in sincronizzazione ${added.length} contributi.`)}catch{alert('Il file selezionato non è un export valido.')}e.target.value=''};
$('#clearBtn').onclick=()=>{if(confirm('Rimuovere dalla vista locale tutti i contributi di questo browser? Le eliminazioni verranno registrate anche nel database.')){[...state.notes,...state.answers,...state.newParts].forEach(item=>queueEvent('delete',item));state.notes=[];state.answers=[];state.newParts=[];saveAndSync()}};
window.addEventListener('online',flushOutbox);
queueUnsyncedExisting();renderAll();flushOutbox();
